### ISSUE TITLE
Access Denied issue

### ISSUE THREAD

**Issue by lakshmanraob** [thestackshack/serverless-stack-cicd#1]
Hi Randy,
  Thanks for the medium post, It is so useful. I started working on the serverless CI/CD, but stuck in running cim stack-up. I started getting the following error.

**cim stack-up**
_{ AccessDeniedException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.
    at Request.extractError (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.',
  code: 'AccessDeniedException',
  time: 2018-05-24T11:07:32.807Z,
  requestId: 'a80f1197-5f42-11e8-a069-114a65b0fdc8',
  statusCode: 400,
  retryable: false,
  retryDelay: 65.09868186058327 }_

Any idea, why this issue is popping up

Thanks
Lakshman

**Comment by rgfindl** [comment]
It sounds like something is wrong with the KMS key.  Did you create your own KMS key and encrypt your github token?  https://github.com/thestackshack/serverless-stack-cicd#encrypt-secrets
